### ISSUE TITLE
Change file structure?

### ISSUE THREAD

**Issue by LCordial** [Ambience-Studios/ambience.mbm#6]
Original:
```
ambience.mbm/
|── src/
|      |── html/
|             |── index.html
|      |── js/
|             |── main.js
|             |── preload.js
|             |── renderer.js
|      |── style/
|             |── main.css
```

New:
```
ambience.mbm/
|── dist/
|      |── html/
|             |── index.html
|      |── js/
|             |── main.js
|             |── preload.js
|             |── renderer.js
|      |── style/
|             |── main.css
|── src/
|      |── main.scss
```

**Reasoning:**
`dist` is short for `distribution`, the files within the `dist` folder would be production-ready and ready for distribution and keeps all the minified files. The `src` file would be all the non-compressed and not compiled versions of the `dist` folder. 

For example: `main.scss -> main.css`

**Comment by RepeatedRoot** [comment]
I think this makes sense to do, plus it might make scss compilation easier cause there are simpler paths to deal with.

**Comment by LCordial** [comment]
I've changed the file structure and created a pull request.
